name: ai_chat_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  google_fonts: ^6.2.1
  flutter_dotenv: ^6.0.0
  intl: 0.20.2
  path: ^1.9.0
  flutter_secure_storage: ^9.2.2
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
  assets:
    - .env
